spring:
  codec:
    max-in-memory-size: 1TB
  application:
    name: cnpj-analyzr-spring-app
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.17.0.2:5432/leaddb}
    username: ${DB_USER:leaduser}
    password: ${DB_PASS:leadpass}
    driver-class-name: org.postgresql.Driver
management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: GET,POST

owner-email: viniciusbaleia1999@gmail.com

mailgun:
  url: ${MAILGUN_URL:test}
  apiKey: ${MAILGUN_APIKEY:test}
  # email to be the host of the email sent by the service
  hostFrom: ${MAILGUN_HOST_FROM:ItiMenu <support@itimenu.app>}

  # Caused by: the request was rejected because its size (3141944029) exceeds the configured maximum (10485760)
